### ISSUE TITLE
⚠️Error ➡️ Resolvers Screen ➡️ UnhandledException

### ISSUE THREAD

**Issue by jamesta696** [instantsc/SimpleDnsCrypt#6] opened 2022-06-19 20:02 UTC
Hi, 
When I'm on the Resolvers Screen, where you pick all your resolvers, when clicking on the Search field to filter through resolvers, I come across an error **"UnhandledException"**.

Reproduce Error: 

1. Click on search field
2. Type in a resolver to filter out (example: Cloudflare)
3. Once resolvers are filtered from the search term, an Error box is presented with "Unhandled Exception".
4. SimpleDNSCrypt crashes

### Here is my Error Screen and Logs when the error occurred:
![image](https://user-images.githubusercontent.com/14171094/174498257-c54aa7b5-16bc-4c6e-a71a-eff0dac6898f.png)

2022-06-19 12:42:11.2134 DnsCryptProxyManager System.InvalidOperationException: Cannot stop 'dnscrypt-proxy' service on computer '.'.
 ---> System.ComponentModel.Win32Exception (1061): The service cannot accept control messages at this time.
   --- End of inner exception stack trace ---
   at System.ServiceProcess.ServiceController.Stop(Boolean stopDependentServices)
   at System.ServiceProcess.ServiceController.Stop()
   at SimpleDnsCrypt.Extensions.ServiceControllerExtensions.StopAsync(ServiceController serviceController, TimeSpan timeout) in D:\a\SimpleDnsCrypt\SimpleDnsCrypt\SimpleDnsCrypt\Extensions\ServiceControllerExtensions.cs:line 17
   at SimpleDnsCrypt.Helper.DnsCryptProxyManager.Stop() in D:\a\SimpleDnsCrypt\SimpleDnsCrypt\SimpleDnsCrypt\Helper\DnsCryptProxyManager.cs:line 124
2022-06-19 12:42:25.6594 ProcessHelper System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Diagnostics.Process.WaitForExitAsync(CancellationToken cancellationToken)
   at SimpleDnsCrypt.Helper.ProcessHelper.ExecuteWithArgumentsAsync(String filename, String arguments) in D:\a\SimpleDnsCrypt\SimpleDnsCrypt\SimpleDnsCrypt\Helper\ProcessHelper.cs:line 158

**Anyway to fix this?
Appreciate your work and help, thanks!**

Edition	Windows 10 Home
Version	21H2
Installed on	‎2/‎19/‎2022
OS build	19044.1741
Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by instantsc** [comment] 2023-03-12 17:00
Honestly not sure if this bug is still present as I am unable to reproduce, but I tried to improve the handling there. I'll close this in a bit unless someone has further information

**Comment by jamesta696** [comment] 2023-03-14 01:30
Hey @instantsc !
I'm closing this issue, as now I'm using Windows 11 Home 22H2 and the issue is not happening anymore :)

Thanks for your hard work in maintaining this project, I appreciate you very much 🙏

**Closed as completed** 2023-03-14 01:34 UTC
